import NavBar from '@/components/NavBar';
import './globals.scss';
import Footer from '@/components/Footer';
import { AOSInit } from '@/components/AOSInit';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <meta name="color-scheme" content="dark" />
            </head>
            <body className="dark">
                <AOSInit />
                <NavBar />
                <div className="px-4">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
