import NavBar from '@/components/NabBar';
import './globals.scss';
import Footer from '@/components/Footer';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <NavBar />
                <main className="px-4">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
